server:
  port: 5555

spring:
  application:
    name: employment
  datasource:
    url: jdbc:mysql://localhost:3306/employments?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
